import LogoutButton from "@/components/logout-button";
import AppSidebar from "@/components/SidebarLayout/AppSidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset className="p-4">
          <SidebarTrigger />
          {children}
          <LogoutButton />
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
